# In _config.yml
title: Machine Learning Methods for Neural Data Analysis
author: Scott Linderman
execute:
  execute_notebooks: force
  exclude_patterns:
    - '01_spike_sorting.ipynb'
only_build_toc_files: true

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# In _config.yml
sphinx:
  config:
    bibtex_reference_style: author_year

# Information about where the book exists on the web
repository:
  url                       : https://github.com/slinderman/stats320  # Online location of your book
  branch                    : winter2023  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"

